version: '3'

tasks: 
  check: 
    desc: "Comprobaci贸n de sintaxis del c贸digo"
    cmds: 
      - "gofmt -e ./pkg/horario > /dev/null"


  build:
    desc: "Compilaci贸n y generaci贸n de binario"
    cmds:
      - "go build ./pkg/horario"

